---
title: Bulma Clean Theme
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    show_sidebar: true
- scope:
    path: ''
    type: posts
  values:
    author: C.S. Rhymes
    layout: post
    image: https://via.placeholder.com/1200x800
    show_sidebar: true
lang: en
tagline: Bulma Clean Theme
email: your-email@domain.com
description: 'The demo site for Bulma Clean Theme, made for Jekyll and GitHub pages
  websites

'
baseurl: "/bulma-clean-theme"
url: https://www.csrhymes.com
permalink: pretty
gh_sponsor: chrisrhymes
paginate: 5
paginate_path: "/blog/page:num"
disqus:
  shortname: csrhymes
plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-feed
- jekyll-seo-tag
- kramdown-parser-gfm
exclude:
- Gemfile
- clean-theme.gemspec
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
livereload: true
sass:
  style: compressed
  source_dir: _sass
markdown: kramdown
highlighter: rouge
footer_menu: example_footer_menu
